### ISSUE TITLE
Cannot import; fails to find file.

### ISSUE THREAD

**Issue by mattsmi** [XRoemer/Organon#106]
Using the extension version 0.9.9.9.0b; LibreOffice version 5.0.3.2; Linux Mint 17.3.

Trying to import file, but each time I select the file, the dialogue box does not keep the file name and so when I click Import, I get an error saying that the file has not been selected.

**Comment by XRoemer** [comment]
Thanks for your report. I'll have a look.


Xaver



Am 21.01.2016 um 10:27 schrieb mattsmi:

**Comment by XRoemer** [comment]
I can confirm the error.

I would have done a new release tonight anyway. The error will be fixed 
than.

Xaver

Am 21.01.2016 um 10:27 schrieb mattsmi:

**Comment by mattsmi** [comment]
New release still coming?
No hurry; it's just that I checked github and couldn't find it.
PS Ich kann auch deutsch, wenn das Ihnen leichter wäre.

**Comment by XRoemer** [comment]
Hi,

yes, the realease is still coming. I'm still busy with a path problem on 
linux and a better debugging setup on my virtualbox, so it might take a 
while. I hope it'll be done till tomorrow.

Thanks for offering using german, but if anyone else likes to read this, 
english might be a better choice.

Xaver



Am 22.01.2016 um 08:50 schrieb mattsmi:

**Comment by XRoemer** [comment]
Hi,

the new release is online now und you can download it directly from here:
http://extensions.openoffice.org/en/project/organon

The import bug should be solved.

Xaver


Am 22.01.2016 um 08:50 schrieb mattsmi:
