### ISSUE TITLE
won't install on ubuntu

### ISSUE THREAD

**Issue by stevepowell99** [XRoemer/Organon#29]
when I try to install, i get 

(com.sun.star.lang.WrappedTargetRuntimeException) { { { Message = "/build/buildd/libreoffice-4.2.7/package/source/zippackage/ZipPackage.cxx:773: Bad Zip File, ZipException: Zip END signature not found!", Context = (com.sun.star.uno.XInterface) @7fa9c8006020 (ImplementationName = "com.sun.star.packages.comp.ZipPackage") } }, TargetException = (any) { (com.sun.star.uno.Exception) { Message = "/build/buildd/libreoffice-4.2.7/package/source/zippackage/ZipPackage.cxx:773: Bad Zip File, ZipException: Zip END signature not found!", Context = (com.sun.star.uno.XInterface) @7fa9c8006020 (ImplementationName = "com.sun.star.packages.comp.ZipPackage") } } }

This is on Ubuntu 14.04, LO 4.2.7.2 420m0(Build:2)

**Comment by XRoemer** [comment]
Did you unzip the downloaded file and install organon.oxt?
For me it works with Ubuntu 14.04, LO 4.2.7.2 420m0(Build:2)

**Comment by stevepowell99** [comment]
thanks that works - the one I downloaded was https://github.com/XRoemer/Organon/blob/master/organon.oxt
