### ISSUE TITLE
Enhancements for the next version

### ISSUE THREAD

**Issue by XRoemer** [XRoemer/Organon#41]
This topic in github issues is more on notating enhancements I made for the next version. So I won't forget..

To make any comments on enhancements, visit:
https://organon4office.wordpress.com/2015/05/26/enhancements-feature-requests/

**Comment by XRoemer** [comment]
Solved Bugs: #39 #40

**Comment by winterlaite** [comment]
Hi, this is a very interesting extension. I would like to see the ability to create a template for new projects. Also, I don't see a Makefile in the source, could you explain how to build it from source?
Regards,
Winter

**Comment by XRoemer** [comment]
Hi, I already wrote some code for templates in earlier versions, but I took it out again, as I wasn't shure, what templates should contain. Only some specific directories and files? Already named? That would be quite easy to realize.
Or should it also contain formattings (like A4, A5, landscape etc)? That's not so easy to realize and is one of the points I like to figure out before v.1.0.
What else is important for templates?

To build the project from source the files have to be packed into an .oxt (LO/OO extension file)
I uploaded my .py file, which builds the extension. But all the paths have to be adjusted and it's a bit messy. Also I'm not shure, if it works for LO completely, as LO crashes soon when I try to start it from a script.

**Comment by winterlaite** [comment]
Hi, thanks for responding so fast!

The thing that really drew me to the project is the idea of tabs. That's 
great! And it's something OpenOffice.org could have incorporated into 
oo.org, but they haven't (IBM gave them the code for Lotus Symphony, 
which already had tabs for Writer).

I'm no expert, but my opinion is that templates should be something the 
end user can customize. What I was thinking was something to make  .ott 
templates that could be pulled in.
I think the most important thing for templates is that they are 
flexible. About format (A4, etc.), I'm sure that could be added later if 
at all.

Also, for me it would be helpful if a new project was as empty as 
possible. I looked in the menus and code, but I couldn't find where to 
change the defaults for a new project. Would it be possible for the end 
user to select what is already filled in for a new project?

I'll try out your .py file, thanks. I look forward to seeing your 
project progress, it's very promising indeed.

Regards,
Winter

**Comment by XRoemer** [comment]
Hi,
I created a new blog entry on my wordpress site, copied our conversation and gave you an answer there: https://organon4office.wordpress.com/2015/05/26/enhancements-feature-requests/

This topic in github issues is more on notating enhancements I made for the next version. So I won't forget...

I will delete my and your entries here and write some notes in the beginning.

**Comment by XRoemer** [comment]
enhancements for v0.9.9.1
After adding Designs for the Organon window, I'll add Designs for the whole Writer application.
Changeable are:
- Statusbar
- Background and foreground of the document
- Sidebar (after clicking on the Organon sidebar entry)
- set Personas with Design (LO only). 
- Create and set Personas within Organon. DONE

Changes are visible after restarting Writer

Unsolvable issues:
- The menubar of OO can't be changed from an extension. 
- Changes will take effect on the other applications of LO/OO within the same session as well.
- No chance to change Design without restart

**Comment by XRoemer** [comment]
Changes:
- Templates: Writer templates can be set and changed afterwards as well. Setting or Removing the file "template.ott" in <project folder>/Files/odt will set or remove a writer template.
